UPDATE shows SET title = "How I Met Your Mother" WHERE title = "How i met your mother";
UPDATE shows SET title = 'Adventure Time' WHERE title LIKE 'adventure time';
UPDATE shows SET title = 'Arrow'WHERE title LIKE 'arrow';
UPDATE shows SET title = 'Avatar: The Last Airbender' WHERE title LIKE 'avatar%';
UPDATE shows SET title = 'Brooklyn Nine-Nine'WHERE title LIKE 'brooklyn%';
UPDATE shows SET title = 'Community'WHERE title LIKE 'community';
UPDATE shows SET title = 'Family Guy' WHERE title LIKE 'family guy';
UPDATE shows SET title = 'Friends' WHERE title LIKE 'friends';
UPDATE shows SET title = 'Game of Thrones' WHERE title LIKE 'game of thrones';
UPDATE shows SET title = 'Gilmore Girls' WHERE title LIKE 'gilmore girls';
UPDATE shows SET title = 'Grey''s Anatomy' WHERE title = 'grey''s anatomy';
UPDATE shows SET title = 'It''s Always Sunny in Philadelphia' WHERE title LIKE ' it''s always sunny%';
UPDATE shows SET title = 'Parks and Recreation' WHERE title LIKE 'parks and%';
UPDATE shows SET title = 'Sherlock' WHERE title LIKE 'sherlock';
UPDATE shows SET title = 'Squid Game' WHERE title LIKE 'squid game';
UPDATE shows SET title = 'The Bachelorette' WHERE title LIKE 'the bach%';
UPDATE shows SET title = 'The Crown' WHERE title LIKE 'the crown%';
UPDATE shows SET title = 'The Office' WHERE title LIKE 'the office';
UPDATE shows SET title = 'The Queen''s Gambit' WHERE title LIKE 'the queen%';
UPDATE shows SET title = 'The Untamed' WHERE title LIKE 'the untamed';